language: scala
scala:
  - 2.11.12
  - 2.12.10
  - 2.13.1

jdk:
  - openjdk8
  - openjdk11

notifications:
  slack: thenewmotion:AXSluctig1mmZbeKRDeeY41s
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
